version: "3.8"
services:
   mongodb:
      image: mongo:latest
      ports:
         - "8094:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: valid-key
         MONGO_INITDB_DATABASE: main-db
      volumes:
         - ./db-scripts:/docker-entrypoint-initdb.d
                
               

