name: Mutation Testing
on:
  workflow_dispatch: {}
  workflow_call:
jobs:
  mutation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.301
        
    - name: Install stryker mutator and Run
      run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet tool install -g dotnet-stryker
          dotnet stryker -O ./reports
    
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: page
        path: ${{ github.workspace }}/reports
        
  deploy-report:
    needs: mutation
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}.
    uses: ./.github/workflows/gh-pages.yml
    secrets: inherit
